title = "Seminario sobre ∞-categorías"
baseURL = "/"
theme = "researcher"
enableEmoji = false
math = true          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = ""
  description = ""
  favicon = "favicon.png"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Times New Roman"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#893101" #changed

[permalinks]
  "/" = "/:filename"

[menu]

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
